### ISSUE TITLE
ModuleNotFoundError: No module named 'dbt.adapters.factory'

### ISSUE THREAD

**Issue by alittlesliceoftom** [PicnicSupermarket/dbt-score#49] opened 2024-06-11 13:48 UTC
Likely lack of pegging release to specific versions of dbt? 

My versions to get above error after doing a straight pip install: 
dbt-adapters              1.2.1
dbt-common                1.3.0
dbt-core                  1.8.2
dbt-extractor             0.5.1
dbt-score                 0.1.3
dbt-semantic-interfaces   0.5.1
dbt-sqlserver             1.4.3
dbt-synapse               1.4.0

**Comment by alittlesliceoftom** [comment] 2024-06-11 13:49
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code        
  File "C:\projects\dbt_clones\dbtenv\Scripts\dbt-score.exe\__main__.py", line 4, in <module>
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt_score\__init__.py", line 3, in <module>
    from dbt_score.models import Model
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt_score\models.py", line 11, in <module>
    from dbt_score.dbt_utils import dbt_ls
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt_score\dbt_utils.py", line 8, in <module>        
    from dbt.cli.main import dbtRunner, dbtRunnerResult
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt\cli\__init__.py", line 1, in <module>
    from .main import cli as dbt_cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt\cli\main.py", line 14, in <module>
    from dbt.cli import requires, params as p
  File "C:\projects\dbt_clones\dbtenv\Lib\site-packages\dbt\cli\requires.py", line 10, in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
ModuleNotFoundError: No module named 'dbt.adapters.factory'

**Comment by matthieucan** [comment] 2024-06-11 16:11
Thanks for the report. It's odd that, looking at the stacktrace, the failure seems to happen in imports only within the dbt-core source code.
Can you share your setup in terms of Python installation? Are you using a virtual environment?

**Comment by alittlesliceoftom** [comment] 2024-06-11 16:14
Venv with python 3.11

*Tom O'Neill*

**Comment by matthieucan** [comment] 2024-06-11 16:15
Does dbt work in that environment? I would suspect it also has import issues?

**Comment by druzhinin-kirill** [comment] 2024-06-12 14:57
Hey! I was able to reproduce this issue on 3.11 with tox :

```
ImportError while loading conftest '.../dbt-score/tests/conftest.py'.
tests/conftest.py:7: in <module>
    from dbt_score import Model, Rule, RuleViolation, Severity, rule
.tox/py310/lib/python3.10/site-packages/dbt_score/__init__.py:3: in <module>
    from dbt_score.models import Model
.tox/py310/lib/python3.10/site-packages/dbt_score/models.py:11: in <module>
    from dbt_score.dbt_utils import dbt_ls
.tox/py310/lib/python3.10/site-packages/dbt_score/dbt_utils.py:8: in <module>
    from dbt.cli.main import dbtRunner, dbtRunnerResult
.tox/py310/lib/python3.10/site-packages/dbt/cli/__init__.py:1: in <module>
    from .main import cli as dbt_cli  # noqa
.tox/py310/lib/python3.10/site-packages/dbt/cli/main.py:14: in <module>
    from dbt.cli import requires, params as p
.tox/py310/lib/python3.10/site-packages/dbt/cli/requires.py:10: in <module>
    from dbt.adapters.factory import adapter_management, register_adapter, get_adapter
E   ModuleNotFoundError: No module named 'dbt.adapters.factory'
```

I believe we are affected by this https://github.com/dbt-labs/dbt-core/issues/10135

As restricting to <1.8 resolves it:

```
"dbt-core>=1.5, <1.8"
```

**Comment by druzhinin-kirill** [comment] 2024-06-28 12:55
Hey! I'll close the issue as it's probably caused by the upstream issue in the `dbt-core`.
Try out some of the suggestions mentioned there and see if it helps you 🙌 
If you continue experiencing the problem or need more information or context, feel free to reopen this issue 👍

**Closed by druzhinin-kirill** 2024-06-28 12:55 UTC

**Comment by mirimgtec** [comment] 2024-09-23 12:00
I am experiencing same issue when trying to use dbt-core 1.8.4 with dbt-metricflow 0.206.0. I am also using dbt-snowflake adapter.

**Comment by matthieucan** [comment] 2024-09-23 12:03
> I am experiencing same issue when trying to use dbt-core 1.8.4 with dbt-metricflow 0.206.0. I am also using dbt-snowflake adapter.

Any chance the hints in https://github.com/dbt-labs/dbt-core/issues/10135 can help?
